<?php
	// $file = file_get_contents("https://www.googleapis.com/language/translate/v2?key=AIzaSyAWztu5VvlwXrTQGcuxLdb2EWzNP6TC-m4&q=hello%20world&source=en&target=hi");
	// print_r(json_decode($file));
	// echo json_decode($file['data']);
	$languages_html = "<tr>
          		<td>Afrikaans</td>
          		<td><code>af</code></td>
        	</tr>
        	 <tr>
        	  <td>Albanian</td>
        	  <td><code>sq</code></td>
        	</tr>
        	<tr>
        	  <td>Arabic</td>
        	  <td><code>ar</code></td>
        	</tr>
        	<tr>
        	  <td>Armenian</td>
        	  <td><code>hy</code></td>
        	</tr>
        	<tr>
        	  <td>Azerbaijani</td>
        	  <td><code>az</code></td>
        	</tr>
        	<tr>
        	  <td>Basque</td>
        	  <td><code>eu</code></td>
        	</tr>
        	<tr>
        	  <td>Belarusian</td>
        	  <td><code>be</code></td>
        	</tr>
        	<tr>
        	  <td>Bengali</td>
        	  <td><code>bn</code></td>
        	</tr>
        	<tr>
        	  <td>Bosnian</td>
        	  <td><code>bs</code></td>
        	</tr>
        	<tr>
        	  <td>Bulgarian</td>
        	  <td><code>bg</code></td>
        	</tr>
        	<tr>
        	  <td>Catalan</td>
        	  <td><code>ca</code></td>
        	</tr>
        	<tr>
        	  <td>Cebuano</td>
        	  <td><code>ceb</code></td>
        	</tr>
        	<tr>
        	  <td>Chichewa</td>
        	  <td><code>ny</code></td>
        	</tr>
        	<tr>
        	  <td>Chinese Simplified</td>
        	  <td><code>zh-CN</code></td>
        	</tr>
        	<tr>
        	  <td>Chinese Traditional</td>
        	  <td><code>zh-TW</code></td>
        	</tr>
        	<tr>
        	  <td>Croatian</td>
        	  <td><code>hr</code></td>
        	</tr>
        	<tr>
        	  <td>Czech</td>
        	  <td><code>cs</code></td>
        	</tr>
        	<tr>
        	  <td>Danish</td>
        	  <td><code>da</code></td>
        	</tr>
        	<tr>
        	  <td>Dutch</td>
        	  <td><code>nl</code></td>
        	</tr>
        	<tr>
        	  <td>English</td>
        	  <td><code>en</code></td>
        	</tr>
        	<tr>
        	  <td>Esperanto</td>
        	  <td><code>eo</code></td>
        	</tr>
        	<tr>
        	  <td>Estonian</td>
        	  <td><code>et</code></td>
        	</tr>
        	<tr>
        	  <td>Filipino</td>
        	  <td><code>tl</code></td>
        	</tr>
        	<tr>
        	  <td>Finnish</td>
        	  <td><code>fi</code></td>
        	</tr>
        	<tr>
        	  <td>French</td>
        	  <td><code>fr</code></td>
        	</tr>
        	<tr>
        	  <td>Galician</td>
        	  <td><code>gl</code></td>
        	</tr>
        	<tr>
        	  <td>Georgian</td>
        	  <td><code>ka</code></td>
        	</tr>
        	<tr>
        	  <td>German</td>
        	  <td><code>de</code></td>
        	</tr>
        	<tr>
        	  <td>Greek</td>
        	  <td><code>el</code></td>
        	</tr>
        	<tr>
        	  <td>Gujarati</td>
        	  <td><code>gu</code></td>
        	</tr>
        	<tr>
        	  <td>Haitian Creole</td>
        	  <td><code>ht</code></td>
        	</tr>
        	<tr>
        	  <td>Hausa</td>
        	  <td><code>ha</code></td>
        	</tr>
        	<tr>
        	  <td>Hebrew</td>
        	  <td><code>iw</code></td>
        	</tr>
        	<tr>
        	  <td>Hindi</td>
        	  <td><code>hi</code></td>
        	</tr>
        	<tr>
        	  <td>Hmong</td>
        	  <td><code>hmn</code></td>
        	</tr>
        	<tr>
        	  <td>Hungarian</td>
        	  <td><code>hu</code></td>
        	</tr>
        	<tr>
        	  <td>Icelandic</td>
        	  <td><code>is</code></td>
        	</tr>
        	<tr>
        	  <td>Igbo</td>
        	  <td><code>ig</code></td>
        	</tr>
        	<tr>
        	  <td>Indonesian</td>
        	  <td><code>id</code></td>
        	</tr>
        	<tr>
        	  <td>Irish</td>
        	  <td><code>ga</code></td>
        	</tr>
        	<tr>
        	  <td>Italian</td>
        	  <td><code>it</code></td>
        	</tr>
        	<tr>
        	  <td>Japanese</td>
        	  <td><code>ja</code></td>
        	</tr>
        	<tr>
        	  <td>Javanese</td>
        	  <td><code>jw</code></td>
        	</tr>
        	<tr>
        	  <td>Kannada</td>
        	  <td><code>kn</code></td>
        	</tr>
        	<tr>
        	  <td>Kazakh</td>
        	  <td><code>kk</code></td>
        	</tr>
        	<tr>
        	  <td>Khmer</td>
        	  <td><code>km</code></td>
        	</tr>
        	<tr>
        	  <td>Korean</td>
        	  <td><code>ko</code></td>
        	</tr>
        	<tr>
        	  <td>Lao</td>
        	  <td><code>lo</code></td>
        	</tr>
        	<tr>
        	  <td>Latin</td>
        	  <td><code>la</code></td>
        	</tr>
        	<tr>
        	  <td>Latvian</td>
        	  <td><code>lv</code></td>
        	</tr>
        	<tr>
        	  <td>Lithuanian</td>
        	  <td><code>lt</code></td>
        	</tr>
        	<tr>
        	  <td>Macedonian</td>
        	  <td><code>mk</code></td>
        	</tr>
        	<tr>
        	  <td>Malagasy</td>
        	  <td><code>mg</code></td>
        	</tr>
        	<tr>
        	  <td>Malay</td>
        	  <td><code>ms</code></td>
        	</tr>
        	<tr>
        	  <td>Malayalam</td>
        	  <td><code>ml</code></td>
        	</tr>
        	<tr>
        	  <td>Maltese</td>
        	  <td><code>mt</code></td>
        	</tr>
        	<tr>
        	  <td>Maori</td>
        	  <td><code>mi</code></td>
        	</tr>
        	<tr>
        	  <td>Marathi</td>
        	  <td><code>mr</code></td>
        	</tr>
        	<tr>
        	  <td>Mongolian</td>
        	  <td><code>mn</code></td>
        	</tr>
        	<tr>
        	  <td>Myanmar (Burmese)</td>
        	  <td><code>my</code></td>
        	</tr>
        	<tr>
        	  <td>Nepali</td>
        	  <td><code>ne</code></td>
        	</tr>
        	<tr>
        	  <td>Norwegian</td>
        	  <td><code>no</code></td>
        	</tr>
        	<tr>
        	  <td>Persian</td>
        	  <td><code>fa</code></td>
        	</tr>
        	<tr>
        	  <td>Polish</td>
        	  <td><code>pl</code></td>
        	</tr>
        	<tr>
        	  <td>Portuguese</td>
        	  <td><code>pt</code></td>
        	</tr>
        	<tr>
        	  <td>Punjabi</td>
        	  <td><code>ma</code></td>
        	</tr>
        	<tr>
        	  <td>Romanian</td>
        	  <td><code>ro</code></td>
        	</tr>
        	<tr>
        	  <td>Russian</td>
        	  <td><code>ru</code></td>
        	</tr>
        	<tr>
        	  <td>Serbian</td>
        	  <td><code>sr</code></td>
        	</tr>
        	<tr>
        	  <td>Sesotho</td>
        	  <td><code>st</code></td>
        	</tr>
        	<tr>
        	  <td>Sinhala</td>
        	  <td><code>si</code></td>
        	</tr>
        	<tr>
        	  <td>Slovak</td>
        	  <td><code>sk</code></td>
        	</tr>
        	<tr>
        	  <td>Slovenian</td>
        	  <td><code>sl</code></td>
        	</tr>
        	<tr>
        	  <td>Somali</td>
        	  <td><code>so</code></td>
        	</tr>
        	<tr>
        	  <td>Spanish</td>
        	  <td><code>es</code></td>
        	</tr>
        	<tr>
        	  <td>Sudanese</td>
        	  <td><code>su</code></td>
        	</tr>
        	<tr>
        	  <td>Swahili</td>
        	  <td><code>sw</code></td>
        	</tr>
        	<tr>
        	  <td>Swedish</td>
        	  <td><code>sv</code></td>
        	</tr>
        	<tr>
        	  <td>Tajik</td>
        	  <td><code>tg</code></td>
        	</tr>
        	<tr>
        	  <td>Tamil</td>
        	  <td><code>ta</code></td>
        	</tr>
        	<tr>
        	  <td>Telugu</td>
        	  <td><code>te</code></td>
        	</tr>
        	<tr>
        	  <td>Thai</td>
        	  <td><code>th</code></td>
        	</tr>
        	<tr>
        	  <td>Turkish</td>
        	  <td><code>tr</code></td>
        	</tr>
        	<tr>
        	  <td>Ukrainian</td>
        	  <td><code>uk</code></td>
        	</tr>
        	<tr>
        	  <td>Urdu</td>
        	  <td><code>ur</code></td>
        	</tr>
        	<tr>
        	  <td>Uzbek</td>
        	  <td><code>uz</code></td>
        	</tr>
        	<tr>
        	  <td>Vietnamese</td>
        	  <td><code>vi</code></td>
        	</tr>
        	<tr>
        	  <td>Welsh</td>
        	  <td><code>cy</code></td>
        	</tr>
        	<tr>
        	  <td>Yiddish</td>
        	  <td><code>yi</code></td>
        	</tr>
        	<tr>
        	  <td>Yoruba</td>
        	  <td><code>yo</code></td>
        	</tr>
        	<tr>
        	  <td>Zulu</td>
        	  <td><code>zu</code></td>
        	</tr>";
    $pattern = '!<tr>.*?<td>(.*?)</td>.*?<td><code>(.*?)</code></td>.*?</tr>!is';
    $replacement = '<option value="$2">$1</option>';
	echo htmlspecialchars(preg_replace($pattern, $replacement, $languages_html));
?>